### ISSUE TITLE
/code endpoint requires having hit root route first

### ISSUE THREAD

**Issue by ashleygwilliams** [mozilla/arch-website#15]
### summary

/code endpoint does not properly load the application. in order to properly load the application one must hit the root route.

### steps to reproduce

1. open an incognito browser (have tested on chrome and firefox)
2. hit https://experiencethearch.com/code
3. see this  <img width="466" alt="screen shot 2018-06-03 at 10 45 32 am" src="https://user-images.githubusercontent.com/1163554/40884828-45759354-671b-11e8-9626-9e86a2b4149e.png">
4. hit https://experiencethearch.com/. page loads.
5. now if you go to the /code endpoint, the page will load.

### notes

the notecards instructed users to hit the /code route directly. this led to most participants first experience in mozilla arch being a 404.

**Comment by joshmarinacci** [comment]
I think this is related to #18 @slightlyoffbeat

**Comment by joshmarinacci** [comment]
This seems to work now. Closing.
